# By default every environment should be production unless changed in _config.local.yml_.
local: production

environments:
  dev:

    # The localized name for this environment.  Messages and filenames will use
    # this instead of "dev".  You may change this to match your workflow.
    id: dev

    export:

      # https://zoomadmin.com/HowToLinux/LinuxCommand/mysqldump
      mysqldump_options:
#        - xml

    reset:
      plugin: pantheon
      files:
        drupal: sites/default/files

  production:

    # The localized name for this environment.  Messages and filenames will use
    # this instead of "dev".  You may change this to match your workflow.
    id: live

    fetch:
      ignore_files_listed_in:
        - drupal.ignore.txt
      plugin: pantheon
      site_name: PANTHEON_SITE_NAME
      site_uuid: PANTHEON_SITE_UUID


