files_sync:
  private:
    - private/default/files
  public:
    - web/sites/default/files

files_copy:
  config:
    -
      local: install/default/.env.$ENV
      remote: .env

# By default every environment should be production unless changed in _config.local.yml_.
local_environment_is: production

environments:
  dev:

    plugin: lando

    # The localized name for this environment.  Messages and filenames will use
    # this instead of "dev".  You may change this to match your workflow.
    id: dev

    export:

      # https://zoomadmin.com/HowToLinux/LinuxCommand/mysqldump
      mysqldump_options:
#        - xml

    reset:
      files:
        drupal: web/sites/default/files

  production:
    label: ENTER_NAME_OF_HOSTING_COMPANY_ETC
    id: live
    plugin: pantheon

    fetch:
      ignore_files_listed_in:
        - drupal.ignore.txt
      site_name: ENTER_PANTHEON_SITE_NAME
      site_uuid: ENTER_PANTHEON_SITE_UUID


