environments:
  dev:
    label: Development
    write_access: true
    plugin: default
    base_path: /alpha/bravo/app
    command_workflows:
      pull: develop
      export: archive
      import: develop
    databases:
      drupal:
        plugin: lando
        service: database
    files:
      install: install/default/scaffold
      secrets: private/default/secrets
      public: web/sites/default/files
      private: private/default/files
  local:
    label: Local Scaffold Source
    write_access: false
    plugin: default
    base_path: /alpha/bravo/app
    files:
      install: .
      secrets: .
  live:
    label: Dreamhost
    write_access: false
    plugin: default
    base_path: /foo/bar/baz/app
    ssh: foo@bar.com
    databases:
      drupal:
        plugin: env
        path: .env
        var: DATABASE_URL
    files:
      install: .
      secrets: .
      public: web/sites/default/files
      private: private/default/files
workflows:
  archive:
    databases:
      drupal:
        exclude_table_data:
          - 'cache*'
  develop:
    databases:
      drupal:
        exclude_table_data:
          - 'cache*'
          - batch
          - config_import
          - config_snapshot
          - key_value_expire
          - sessions
          - watchdog
      file_groups:
        - install
        - secrets
        - public
        - private
      processors:
        - FileGroupHandler::process
        - prepare_db_for_dev.sh
        - replace_dumpfile.sh
file_groups:
  install:
    include:
      - /web/.htaccess
      - /web/sites/default/settings.local.php
      - /.env
  secrets:
    include:
      - /web/sites/default/settings.local.php
      - /.env
  public:
    exclude:
      - /.DS_Store
      - '/config_*/'
      - /css/
      - /imagecache/
      - /js/
      - /php/
      - /styles/
      - /tmp/
  private:
    exclude:
      - /tmp/
