files_copy:
#  config:
#    - install/default/.env.$ENV .env

# By default every environment should be production unless changed in _config.local.yml_.
local_environment_is: production

environments:
  dev:

    plugin: default

    # The localized name for this environment.  Messages and filenames will use
    # this instead of "dev".  You may change this to match your workflow.
    id: dev

    files_sync:
      public:
        - web/sites/default/files
      private:
        - private/default/files

    export:

      # https://zoomadmin.com/HowToLinux/LinuxCommand/mysqldump
      mysqldump_options:
  #        - xml

  production:
    label: ENTER_NAME_OF_HOSTING_COMPANY_ETC
    id: live
    user: USERNAME
    host: REMOTE_HOST
    base_path: PATH_TO_APP

    files_sync:
      public:
        - files
      private:
        - files/private

#    fetch:
#      site_name: ENTER_PANTHEON_SITE_NAME
#      site_uuid: ENTER_PANTHEON_SITE_UUID


