environments:
  -
    id: local
    label: Local
    write_access: true
    plugin: lando
    files:
      secrets: private/default/secrets
      install: install/default
      public: web/sites/default/files
      private: private/default/files
    databases:
      default:
        host: TODO
        port: TODO
        name: TODO

  -
    id: live
    label: Dreamhost
    write_access: false
    plugin: default
    files:
      public: web/sites/default/files
      private: private/default/files

file_groups:
  -
    id: secrets
    include:
      - /.env
      - /bin/config/*.local.*
      - /.loft_deploy/config.yml
  -
    id: install
    include:
      - /web/.htaccess
      - /.env
      - /bin/config/*.local.*
      - /.loft_deploy/config.yml
  -
    id: public
    exclude:
      - .DS_Store
      - config_*
      - css/
      - imagecache/
      - js/
      - php/
      - styles/
      - tmp
  -
    id: private
