# Defines the type of environment for the local instance; cannot be changed via
# CLI arguments.
local_environment_is: dev

# Defines the remote environment, this may be altered by CLI arguments.  This must be one of the keys defined in config.yml
remote_environment_is: production

environments:
  dev:
    label: LOCALIZED_TITLE_IF_DESIRED

    database:
      protocol: tcp
      host: HOST
      port: PORT
      name: DB_NAME
      user: USER
      pass: PASSWORD

  production:
    name: LOCALIZED_TITLE_IF_DESIRED
    fetch:
      machine_token: MACHINE_TOKEN_FROM_PANTHEON
