old.environments:
  dev:
    plugin: default
    id: dev
    name: 'Local development'
    export:
      path: .live_dev_porter/backups
      exclude_data_from_tables_listed_in:
        - data_exclusions.txt
      exclude_tables_listed_in:
        - table_exclusions.txt
    fetch:
      path: .live_dev_porter/fetch
  staging:
    plugin: default
    id: test
    name: Staging
  production:
    plugin: default
    id: production
    name: Production
