<?php
/* SPDX-License-Identifier: BSD-3-Clause */

/**
 * @file
 * Write a bash config file based on JSON.
 *
 * This is the second step in the configuration compiling.
 *
 * @group configuration
 * @see normalize.php
 */

use AKlump\LoftLib\Bash\Configuration;

$namespace = $argv[2] ?? NULL;
$json = $argv[3] ?? NULL;

if (empty($json)) {
  fail_because("JSON is empty; cannot parse an empty configuration string.");
  return;
}

$data = json_decode($json, TRUE);
if ($data === NULL) {
  fail_because("Invalid JSON: \"$json\"");
  return;
}

$context = ['stack' => []];
$context['stack'][] = "#!/usr/bin/env bash\n";
$context['stack'][] = "#\n# @file\n# Autogenerated configuration; DO NOT EDIT.\n#\n";

$var_service = new Configuration($namespace, '.');
$stack = $var_service->flatten($data, $context);
echo implode(PHP_EOL, $stack);
